namespace BasicFtpServer.App.Tray;

public enum TrayState
{
    Running,
    Warning,
    Stopped,
}

/// <summary>
/// Icon resources.
///
/// The artwork is generated by tools\generate-icons.ps1 rather than drawn at runtime, so
/// the notification area, the Start Menu shortcut, window title bars and the installer all
/// show the same glyph. The tray variants differ only in colour, which is what carries the
/// status: green running, amber degraded, red stopped.
/// </summary>
public static class TrayIcons
{
    private static readonly Lock Gate = new();
    private static readonly Dictionary<string, Icon> Cache = [];

    /// <summary>Status icon for the notification area, sized for the current DPI.</summary>
    public static Icon For(TrayState state) => Load(
        state switch
        {
            TrayState.Running => "TrayRunning.ico",
            TrayState.Warning => "TrayWarning.ico",
            _ => "TrayStopped.ico",
        },
        SystemInformation.SmallIconSize);

    /// <summary>The neutral application icon, for window title bars and alt-tab.</summary>
    public static Icon Window => Load("App.ico", SystemInformation.IconSize);

    private static Icon Load(string resourceName, Size size)
    {
        var key = $"{resourceName}@{size.Width}x{size.Height}";

        lock (Gate)
        {
            if (Cache.TryGetValue(key, out var cached))
            {
                return cached;
            }

            using var stream = typeof(TrayIcons).Assembly.GetManifestResourceStream(resourceName)
                ?? throw new InvalidOperationException($"Embedded icon '{resourceName}' is missing.");

            // Selecting the size explicitly picks the matching frame out of the .ico instead
            // of letting WinForms scale whichever one it happens to take first.
            var icon = new Icon(stream, size);
            Cache[key] = icon;
            return icon;
        }
    }
}
