<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>basic-ftp-server</AssemblyName>
    <RootNamespace>BasicFtpServer.Mac</RootNamespace>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BasicFtpServer.Core\BasicFtpServer.Core.csproj" />
  </ItemGroup>
</Project>
